name: Name 1

states:
 - A
 - B
 - C
start_states:
 A: 0.7
 B: 0.3

final_states:
 C: 1

transition_probability:
 A:
  B: 1
 B:
  A: 0.75
  C: 0.25

diagnoses:
 A:
  a1: 0.2
  a2: 0.3
  a3: 0.5
 B:
  b1: 0.35
  b2: 0.65
 C:
  c1: 0.1
  c2: 0.6
  c3: 0.3
